# Config 사용
spring:
  config:
    import: "optional:configserver:"    # configserver import 활성화

  cloud:
    config:
      enabled: true
      profile: prod # config-repo의 prod 프로필 사용
      label: main   # config-repo 의 main 브랜치 사용
      discovery:
        enabled: true                   # Eureka를 통해 Config Server 찾기
        service-id: chaekmate-config    # Eureka 서비스 이름
      fail-fast: true # Config server 못찾을시 중단

