# Gateway/Target Server Port (prod) : "배포설명" 확인

# Gateway Server Port
server:
  port: ${PORT_NUMBER}

# Target Server (Eureka Server) URL
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL_PROD}

logging:
  level:
    root: info